version: '3.8'
services:
  app:
    image: learning/app:v1
    command: "/usr/bin/supervisord -c /etc/supervisord.conf"
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ../app:/opt/app
      - ../nginx/conf/main.conf:/etc/nginx/nginx.conf
      - ../nginx/conf/app.conf:/etc/nginx/conf.d/app.conf
      - ../supervisor/conf/main.conf:/etc/supervisord.conf
      - ../supervisor/conf/app.ini:/etc/supervisord.d/app.ini
      - ../supervisor/conf/nginx.ini:/etc/supervisord.d/nginx.ini
    depends_on:
      - redis
    networks:
      common:
        ipv4_address: ${APP_IP}
  redis:
    image: learning/redis:v1
    command: "/usr/bin/supervisord -c /etc/supervisord.conf"
    volumes:
      - redis-data:/opt/redis/data
      - redis-log:/opt/redis/log
      - ../redis/conf/main.conf:/opt/redis/conf/redis.conf
      - ../supervisor/conf/main.conf:/etc/supervisord.conf
      - ../supervisor/conf/redis.ini:/etc/supervisord.d/redis.ini
    networks:
      common:
        ipv4_address: ${REDIS_IP}
volumes:
  redis-data:
    driver: local
  redis-log:
    driver: local
networks:
  common:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK}
